version: "3.8"

services:
  #node.js
  node:
    container_name: node
    # for Apple Silicon Mac
    # platform: linux/arm64/v8
    build:
      context: ./node
      dockerfile: Dockerfile
    volumes:
      - ./node:/app
      - node_modules_volume:/app/node_modules:delegated
    tty: true
    ports:
      - 80:80
    environment:
      - TZ=Asia/Tokyo

  #ngrok(LINEbot ローカル動作確認用)
  ngrok:
    container_name: ngrok
    image: wernight/ngrok:latest
    volumes:
      - ./ngrok.yml:/home/ngrok/.ngrok2/ngrok.yml
    ports:
      - 4040:4040
    environment:
      NGROK_PORT: node:80
      NGROK_AUTH: ${NGROK_AUTH_TOKUN}
    networks:
      - default

  # Python
  # python:
  #   container_name: python
  #   build:
  #     context: ./
  #     dockerfile: ./py/Dockerfile
  #   working_dir: /work
  #   volumes:
  #   - ./py:/work
  #   ports:
  #   - "8888:8888"
  #   tty: true
  #   stdin_open: true

  # FastAPI
  fastapi:
    container_name: "fastapi"
    volumes:
      - ./fastapi:/app
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    tty: true
    stdin_open: true

volumes:
  node_modules_volume:
